name: Dockerize Laravel Application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to github Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/laravel
          tags: latest, ${{ github.run_number }}
      - name: Publish to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: Crushoverride007/laraveldevops
          tags: latest, ${{ github.run_number }}

