on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  tenablecs-scan:
    runs-on: ubuntu-latest
    name: tenablecs-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tenable.cs Scan
        id: tenablecs-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://app.accurics.com/v1/api/terrascan
          webhook_token: d525e7f3-1cf9-46e2-97e5-364571eb3e1c